dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - gcc-8
      - g++-8
      - cmake
      - cmake-data
before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.10/cmake-3.10.0-rc1-Linux-x86_64.sh
  - chmod +x cmake-3.10.0-rc1-Linux-x86_64.sh
  - ./cmake-3.10.0-rc1-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - cd CK2ToEU4
  - cmake -H. -Bbuild
  - cmake --build ./build -- -j3