l_english:
 DISPLAYNAME: "Crusader Kings II To Europa Universalis IV"
 SOURCEGAME: "Crusader Kings II"
 TARGETGAME: "Europa Universalis IV"
 FOLDER1: "Crusader Kings II Install directory"
 FOLDER1TIP: "A path on your computer where Crusader Kings 2 is installed"
 FOLDER2: "Crusader Kings II Mods Directory"
 FOLDER2TIP: "A path on your computer where Crusader Kings II keeps mods"
 FOLDER3: "Europa Universalis IV Install directory"
 FOLDER3TIP: "A path on your computer where Europa Universalis IV is installed"
 FOLDER4: "Europa Universalis IV Mods directory"
 FOLDER4TIP: "A path on your computer where Europa Universalis IV keeps mods"
 FILE1: "Path to the converter executable"
 FILE1TIP: "Path to CK2ToEU4Converter.exe"
 FILE2: "Path to the CK2 Savegame"
 FILE2TIP: "Path to your savegame from CK2"
