l_french:
 DISPLAYNAME: "Crusader Kings II à Europa Universalis IV"
 SOURCEGAME: "Crusader Kings II"
 TARGETGAME: "Europa Universalis IV"
 FOLDER1: "Répertoire d'installation de Crusader Kings II"
 FOLDER1TIP: "Un chemin sur votre ordinateur où Crusader Kings 2 est installé"
 FOLDER2: "Répertoire des mods de Crusader Kings II"
 FOLDER2TIP: "Un chemin sur votre ordinateur où Crusader Kings II conserve les mods"
 FOLDER3: "Répertoire d'installation d'Europa Universalis IV"
 FOLDER3TIP: "Un chemin sur votre ordinateur où Europa Universalis IV est installé"
 FOLDER4: "Répertoire des Mods Europa Universalis IV"
 FOLDER4TIP: "Un chemin sur votre ordinateur où Europa Universalis IV conserve les mods"
 FILE1: "Chemin vers l'exécutable du convertisseur"
 FILE1TIP: "Chemin d'accès à CK2ToEU4Converter.exe"
 FILE2: "Chemin vers le jeu de sauvegarde CK2"
 FILE2TIP: "Chemin vers votre sauvegarde depuis CK2"
